# Generated by Django 4.2.23 on 2026-08-01 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Vendor device identifier', max_length=100, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('sensor_type', models.CharField(choices=[('soil_moisture', 'Soil moisture'), ('soil_temperature', 'Soil temperature'), ('air_temperature', 'Air temperature'), ('air_humidity', 'Air humidity'), ('rainfall', 'Rainfall')], default='soil_moisture', max_length=30)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sensor_device',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(help_text='Measurement in the device unit')),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='sensors.sensordevice')),
            ],
            options={
                'db_table': 'sensor_reading',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['device', '-recorded_at'], name='idx_reading_device_time')],
            },
        ),
        migrations.AddIndex(
            model_name='sensordevice',
            index=models.Index(fields=['owner', 'sensor_type'], name='idx_sensor_owner_type'),
        ),
    ]
