# Generated by Django 4.2.23 on 2026-08-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordevice',
            name='crop',
            field=models.CharField(blank=True, default='', help_text='Crop grown at this sensor (for irrigation thresholds)', max_length=50),
        ),
        migrations.AddField(
            model_name='sensordevice',
            name='last_irrigation_alert_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
