# Generated by Django 4.2.23 on 2026-08-01 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0004_payment_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('external', 'External clearing (mobile money)'), ('escrow', 'Platform escrow'), ('dealer', 'Dealer balance'), ('farmer', 'Farmer balance'), ('platform', 'Platform fee / income')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledger_account',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to='ledger.account')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries', to='ledger.account')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payments.payment')),
            ],
            options={
                'db_table': 'ledger_entry',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['debit', '-created_at'], name='idx_ledger_debit'), models.Index(fields=['credit', '-created_at'], name='idx_ledger_credit'), models.Index(fields=['payment'], name='idx_ledger_payment')],
            },
        ),
    ]
