# Generated by Django 6.0.7 on 2026-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('temperature', models.FloatField()),
                ('feels_like', models.FloatField(default=0)),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('condition', models.CharField(default='', max_length=100)),
                ('rain_probability', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=100)),
                ('farming_advice', models.TextField(default='')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weather_data',
                'ordering': ['-fetched_at'],
            },
        ),
    ]
