from rest_framework import viewsets, status, permissions
from rest_framework.exceptions import PermissionDenied
from rest_framework.response import Response
from rest_framework.decorators import action

from .models import Announcement, Notification
from .serializers import AnnouncementSerializer, NotificationSerializer


class AnnouncementViewSet(viewsets.ModelViewSet):
    queryset = Announcement.objects.all()
    serializer_class = AnnouncementSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        if user.role == 'admin':
            return Announcement.objects.all()

        # Filter by target audience
        if user.role == 'farmer':
            return Announcement.objects.filter(is_active=True, target_audience__in=['all', 'farmers'])
        elif user.role == 'dealer':
            return Announcement.objects.filter(is_active=True, target_audience__in=['all', 'dealers'])
        return Announcement.objects.filter(is_active=True, target_audience='all')

    def perform_create(self, serializer):
        if self.request.user.role != 'admin':
            raise PermissionDenied('Only admins can create announcements')
        serializer.save(created_by=self.request.user)

    def perform_update(self, serializer):
        if self.request.user.role != 'admin':
            raise PermissionDenied('Only admins can update announcements')
        serializer.save()

    def perform_destroy(self, instance):
        if self.request.user.role != 'admin':
            raise PermissionDenied('Only admins can delete announcements')
        instance.delete()

    @action(detail=False, methods=['get'])
    def active(self, request):
        """Get only active announcements for the current user."""
        announcements = self.get_queryset().filter(is_active=True)
        serializer = self.get_serializer(announcements, many=True)
        return Response(serializer.data)

    @action(detail=True, methods=['post'])
    def toggle_active(self, request, pk=None):
        """Admin toggles announcement visibility (enable/disable broadcast)."""
        if request.user.role != 'admin':
            return Response({'error': 'Admin only'}, status=status.HTTP_403_FORBIDDEN)
        announcement = self.get_object()
        announcement.is_active = not announcement.is_active
        announcement.save(update_fields=['is_active'])
        return Response({'is_active': announcement.is_active})


class NotificationViewSet(viewsets.ModelViewSet):
    """The authenticated user's in-app notifications.

    Notifications are created system-side (order placed, payment confirmed,
    premium activated...). Users may only list/read their own.
    """

    queryset = Notification.objects.all()
    serializer_class = NotificationSerializer
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return Notification.objects.filter(recipient=self.request.user)

    def create(self, request, *args, **kwargs):
        raise PermissionDenied('Notifications are generated by the system')

    def update(self, request, *args, **kwargs):
        raise PermissionDenied('Notifications cannot be edited')

    def partial_update(self, request, *args, **kwargs):
        raise PermissionDenied('Notifications cannot be edited')

    def destroy(self, request, *args, **kwargs):
        raise PermissionDenied('Notifications cannot be deleted by users')

    @action(detail=False, methods=['get'])
    def unread_count(self, request):
        count = self.get_queryset().filter(is_read=False).count()
        return Response({'count': count})

    @action(detail=True, methods=['post'])
    def mark_read(self, request, pk=None):
        notification = self.get_object()
        notification.is_read = True
        notification.save(update_fields=['is_read'])
        return Response({'is_read': True})

    @action(detail=False, methods=['post'])
    def mark_all_read(self, request):
        self.get_queryset().filter(is_read=False).update(is_read=True)
        return Response({'status': 'ok'})
