# Generated by Django 4.2.23 on 2026-07-31 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['farmer', '-created_at'], name='idx_order_farmer'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['product', '-created_at'], name='idx_order_product'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['dealer', 'is_available', '-created_at'], name='idx_product_dealer_avail'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='idx_product_cat_avail'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='order_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('total_price__gte', 0)), name='order_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='product_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(check=models.Q(('stock_quantity__gte', 0)), name='product_stock_non_negative'),
        ),
    ]
