# Generated by Django 4.2.23 on 2026-09-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_review_productreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_key',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('farmer', 'checkout_key'), name='uniq_farmer_checkout'),
        ),
    ]
