# Generated by Django 4.2.23 on 2026-07-31 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('order', 'Marketplace Order'), ('premium', 'Premium Subscription')], default='order', max_length=20),
        ),
    ]
