# Generated by Django 4.2.23 on 2026-09-06 06:25

from django.db import migrations, models
import uuid


def preserve_existing_references(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    # The previous adapter derived UUIDv5 IDs. Keep those IDs for historical
    # rows so any already-submitted collections can still be reconciled.
    # New attempts get a persisted UUIDv4, as required by MTN.
    for row in Payment.objects.using(schema_editor.connection.alias).all().iterator():
        row.provider_reference = uuid.uuid5(uuid.NAMESPACE_URL, row.transaction_id)
        row.save(using=schema_editor.connection.alias, update_fields=['provider_reference'])


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_environment',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_reference',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(preserve_existing_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='payment', name='provider_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('review_required', 'Collected - manual review required')], default='pending', max_length=20),
        ),
    ]
