# Generated by Django 6.0.7 on 2026-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('crop_type', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diagnosis_images/')),
                ('symptoms', models.TextField(blank=True, default='')),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('disease_name', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('causes', models.TextField(blank=True, default='')),
                ('prevention', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diagnosis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('address', models.CharField(max_length=255)),
                ('climate_zone', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(blank=True, default='', max_length=100)),
                ('medication', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('duration', models.IntegerField(default=14, help_text='Duration in days')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'treatment_plan',
            },
        ),
    ]
