# Generated by Django 6.0.7 on 2026-07-24 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnoses', to='diagnosis.location'),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='diagnosis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plan', to='diagnosis.diagnosis'),
        ),
    ]
