# Generated by Django 6.0.7 on 2026-07-28 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('crop_name', models.CharField(max_length=100)),
                ('pathogen', models.CharField(blank=True, default='', max_length=200)),
                ('symptoms', models.TextField(blank=True, default='')),
                ('causes', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('prevention', models.TextField(blank=True, default='')),
                ('treatment_type', models.CharField(blank=True, default='', max_length=100)),
                ('medication', models.TextField(blank=True, default='')),
                ('instructions', models.TextField(blank=True, default='')),
                ('duration', models.IntegerField(default=14, help_text='Duration in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_diseases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disease',
                'ordering': ['disease_name'],
            },
        ),
    ]
