# Generated by Django 4.2.23 on 2026-08-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0003_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='is_healthy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='is_inconclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('unknown', 'Unknown')], default='low', max_length=20),
        ),
    ]
