# Generated by Django 4.2.23 on 2026-08-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_diagnosis_is_healthy_diagnosis_is_inconclusive_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutbreakAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('crop_name', models.CharField(blank=True, default='', max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_km', models.IntegerField(default=50)),
                ('cluster_size', models.IntegerField(default=0)),
                ('previous_size', models.IntegerField(default=0)),
                ('notified_users', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('notified', 'Notified'), ('expired', 'Expired')], default='active', max_length=20)),
                ('cooldown_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'outbreak_alert',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='idx_outbreak_status'), models.Index(fields=['disease_name', 'latitude', 'longitude'], name='idx_outbreak_disease_loc')],
            },
        ),
    ]
