# Generated by Django 4.2.23 on 2026-09-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_diagnosis_inference_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='crop_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='detected_crop',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='visual_evidence',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
