# Generated by Django 4.2.23 on 2026-08-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_idx_user_role_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('purpose', models.CharField(choices=[('register', 'Account registration'), ('password_reset', 'Password reset')], default='register', max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose', 'is_used'], name='idx_otp_phone_purpose')],
            },
        ),
    ]
